### ISSUE TITLE
Continuously read packets from multicast udp stream and extract data

### ISSUE THREAD

**Issue by maximk-1** [Comcast/gots#153]
Hi.
Is it possible to continuously read packets from multicast udp stream and extract data, ex. for scte35 logging?

**Comment by LimitlessEarth** [comment]
Hello,
Yes. 
Here is some pseudo code that shows roughly what you would do

```
pkt := &packet.Packet{}

accumulator := libpacket.NewAccumulator(scte35.SCTE35AccumulatorDoneFunc)

for {
	bytesRead, err = socket.Read(readBuf)
	if err != nil {
		return err
	}

	for pi = 0; pi < (bytesRead / packet.PacketSize); pi++ {
		copy(pkt[:], readBuf[pi*packet.PacketSize:(pi+1)*packet.PacketSize])

		_, err := accumulator.WritePacket(pkt)
		if err == gots.ErrAccumulatorDone {
			message, err := scte35.NewSCTE35(accumulator.Bytes())
			if err != nil {
				accumulator.Reset()
				continue
			}
			fmt.Println(message)
			accumulator.Reset()
		}
	}
}
```

I would recommend more error checking but that the basics of it.
- Read []byte off of your udp connection/socket
- Split the []byte into packet.Packets
- Look for your scte pid potentially
- Accumulate a SCTE message
- log/print it
- repeat

I'm going to close this because it is not an issue.

**Comment by LimitlessEarth** [comment]
Other errors you could check are:
- socket Reading
- bytesRead % packet.PacketSize (is the data you got back MPEG2-TS packets?)
- Accumulator errors
- etc.
